[project]
name = "vibebolt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "docker>=7.1.0",
    "fastmcp>=2.2.1",
    "ruff>=0.11.6",
]
